name: Deploy to Development server

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install sshpass
      run: sudo apt-get install -y sshpass


    - name: Install knockd
      run: sudo apt-get install -y knockd

    - name: Send port-knocking sequence
      run: knock -v srv5299.mjhst.com 6335 3278 7524

    - name: Deploy to VPS
      run: sshpass -p ${{ secrets.SSH_PASSWORD }} ssh dev_ftp@srv5299.mjhst.com 'cd ./../httpd/html/dev.fetishonly.com/public_html/deployment/ && ./deploy.sh'
